Update building.md
skiftOS/skift pull request #207
Opened 2020-11-12 07:37 UTC by HexaOneOfficial

fix some typo's and other small things

2020-11-12 07:40 UTC, Keyboard-Slayer requested changes

2020-11-12 07:40 UTC, Keyboard-Slayer commented on building.md
> +Or if you already cloned this repo without `--recursive` do:
`if you have already` cloned will be better I think

2020-11-12 07:40 UTC, Keyboard-Slayer commented on building.md
> +This command will build all the components of the project and generate an bootable ISO in QEMU or VirtualBox.
`a bootable ISO`

2020-11-14 23:57 UTC, caelwithcats commented
```
This branch has no conflicts with the base branch
```
so why did you add the `stale` tag?

2020-11-15 00:04 UTC, sleepy-monax commented
It's stale because the discussion are marked as resolved but there is not commit, wich fix the issues brought by the reviewer

2020-11-15 07:31 UTC, HexaOneOfficial commented
sure close it than?

2020-11-15 07:47 UTC, caelwithcats commented
@HexaOneOfficial just add more commits to this PR

2020-11-22 16:07 UTC, closed without merging