Change onboarding grammar and change username "anon" to "User"
skiftOS/skift pull request #235
Opened 2021-01-05 04:06 UTC by pixl-8

This will make it easier for users to understand the OS.

2021-01-05 15:04 UTC, notYuriy requested changes

2021-01-05 15:04 UTC, notYuriy commented on apps/onboarding/content3.markup
> +        <Label text="contributing code, reporting issues, donations and sponsorship." anchor="center"/>
`reporting issues, donations, and sponsorship.`
Add oxford comma here.

2021-01-05 15:04 UTC, notYuriy commented on apps/onboarding/content1.markup
> +        <Label text="Checkout the terminal with familiar unix utilities" anchor="center"/>
`Checkout` should be written as `Check out`. I would suggest using `Try out` instead.

2021-01-05 15:08 UTC, notYuriy commented on sysroot/Configs/environment.json
> +        "LOGNAME": "User",
User name starting from capital case may be not very terminal friendly.

2021-01-05 15:08 UTC, notYuriy commented on apps/onboarding/content2.markup
> +        <Label text="Github, Discord, and Twitter at #skiftOS." anchor="center"/>
Why `at` is used instead of `on`?

2021-01-06 22:45 UTC, closed without merging

2021-01-08 00:19 UTC, pixl-8 reviewed
Sorry, I was in a rush when I checked this.